-- Copyright (c) 2023 Tampere University.
--
-- Module generated by OpenASIP.
--
-- Permission is hereby granted, free of charge, to any person obtaining a
-- copy of this software and associated documentation files (the "Software"),
-- to deal in the Software without restriction, including without limitation
-- the rights to use, copy, modify, merge, publish, distribute, sublicense,
-- and/or sell copies of the Software, and to permit persons to whom the
-- Software is furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
-- DEALINGS IN THE SOFTWARE.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.tta0_globals.all;


entity rv32_microcode is
port(
  clk            : in std_logic;
  rstx           : in std_logic;
  glock_in       : in std_logic;
  data_hazard_in : in std_logic;
  rs1_hazard_in  : in std_logic;
  rs2_hazard_in  : in std_logic;
  halt           : in std_logic;
  fu_opcode_in : in  std_logic_vector(16 downto 0);
  moves_out    : out std_logic_vector(INSTRUCTIONWIDTH-1 downto 0));

end rv32_microcode;

architecture rtl of rv32_microcode is
  signal fu_opcode : std_logic_vector(16 downto 0);
  signal moves     : std_logic_vector(INSTRUCTIONWIDTH-1 downto 0);
  constant rs1_start_c : integer := 9;
  constant rs2_start_c : integer := 0;
  constant rs1_width_c : integer := 12;
  constant rs2_width_c : integer := 9;
  signal target_fu : unsigned(3-1 downto 0);
  signal target_fu_r : unsigned (3-1 downto 0);
  signal data_hazard : std_logic;
  signal rs1_hazard : std_logic;
  signal rs2_hazard : std_logic;

  begin

  fu_opcode  <= fu_opcode_in;
  moves_out  <= moves;

  data_hazard <= data_hazard_in;
  rs1_hazard  <= rs1_hazard_in;
  rs2_hazard  <= rs2_hazard_in;

  process(fu_opcode)
  begin
    target_fu <= to_unsigned(0, 3);
    if fu_opcode(17-1 downto 0)= "00000011100110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000011000110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000010110110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000010000110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000010100110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000011010110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000011110110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000010010110011" then
      target_fu <= to_unsigned(0, 3);
    elsif fu_opcode(17-1 downto 0)= "00000000000001011" then
      target_fu <= to_unsigned(1, 3);
    elsif fu_opcode(10-1 downto 0)= "0001100111" then
      target_fu <= to_unsigned(2, 3);
    elsif fu_opcode(7-1 downto 0)= "1101111" then
      target_fu <= to_unsigned(2, 3);
    elsif fu_opcode(17-1 downto 0)= "01000000000110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(17-1 downto 0) = "00000001010010011"  or fu_opcode = "00000001010110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(17-1 downto 0) = "00000000010010011"  or fu_opcode = "00000000010110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(10-1 downto 0) = "1110010011"  or fu_opcode = "00000001110110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(10-1 downto 0) = "1000010011"  or fu_opcode = "00000001000110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(10-1 downto 0) = "1100010011"  or fu_opcode = "00000001100110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(10-1 downto 0) = "0100010011"  or fu_opcode = "00000000100110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(10-1 downto 0) = "0000010011" or fu_opcode = "00000000000110011" or fu_opcode(7-1 downto 0) = "0110111" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(10-1 downto 0) = "0110010011"  or fu_opcode = "00000000110110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(17-1 downto 0) = "01000001010010011"  or fu_opcode = "01000001010110011" then
      target_fu <= to_unsigned(3, 3);
    elsif fu_opcode(10-1 downto 0)= "1010000011" then
      target_fu <= to_unsigned(4, 3);
    elsif fu_opcode(10-1 downto 0)= "0000000011" then
      target_fu <= to_unsigned(4, 3);
    elsif fu_opcode(10-1 downto 0)= "0010000011" then
      target_fu <= to_unsigned(4, 3);
    elsif fu_opcode(10-1 downto 0)= "0100000011" then
      target_fu <= to_unsigned(4, 3);
    elsif fu_opcode(10-1 downto 0)= "1000000011" then
      target_fu <= to_unsigned(4, 3);
    elsif fu_opcode(7-1 downto 0)= "0010111" then
      target_fu <= to_unsigned(5, 3);
    end if;
  end process;


  process(clk, rstx)
  begin
    if(rstx = '0') then
      target_fu_r <= (others => '0');
    elsif clk'event and clk = '1' then
      if glock_in = '0' and halt = '0' then
        target_fu_r <= target_fu;
      end if;
    end if;
  end process;


  process(fu_opcode, data_hazard, rs1_hazard, rs2_hazard, target_fu_r)
  begin
    if(fu_opcode = "01000000000110011")  then
      moves <= "1010000011000000000000001000000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000001010110011") then
      moves <= "1010000011000000000000000111000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000000010110011") then
      moves <= "1010000011000000000000000101000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000001110110011") then
      moves <= "1010000011000000000000000001000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000000000001011") then
      moves <= "1010000101000000000000110000000000100";
    elsif(fu_opcode(17 - 1 downto 0) = "00000011100110011") then
      moves <= "1010000110000000000000011110000000101";
    elsif(fu_opcode(17 - 1 downto 0) = "00000001000110011") then
      moves <= "1010000011000000000000001001000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000011000110011") then
      moves <= "1010000110000000000000011000000000101";
    elsif(fu_opcode(17 - 1 downto 0) = "00000001100110011") then
      moves <= "1010000011000000000000000010000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000010110110011") then
      moves <= "1010000110000000000000011101000000101";
    elsif(fu_opcode(17 - 1 downto 0) = "00000000100110011") then
      moves <= "1010000011000000000000000011000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000000000110011") then
      moves <= "1010000011000000000000000000000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000000110110011") then
      moves <= "1010000011000000000000000100000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "01000001010110011") then
      moves <= "1010000011000000000000000110000000010";
    elsif(fu_opcode(17 - 1 downto 0) = "00000010000110011") then
      moves <= "1010000110000000000000011010000000101";
    elsif(fu_opcode(17 - 1 downto 0) = "00000010100110011") then
      moves <= "1010000110000000000000011100000000101";
    elsif(fu_opcode(17 - 1 downto 0) = "00000011010110011") then
      moves <= "1010000110000000000000011001000000101";
    elsif(fu_opcode(17 - 1 downto 0) = "00000011110110011") then
      moves <= "1010000110000000000000011111000000101";
    elsif(fu_opcode(17 - 1 downto 0) = "00000010010110011") then
      moves <= "1010000110000000000000011011000000101";
    elsif(fu_opcode(10 - 1 downto 0) = "1000010011") then
      moves <= "0010100011000000000000001001100000000";
    elsif(fu_opcode(17 - 1 downto 0) = "00000001010010011") then
      moves <= "0010100011000000000000000111100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "1110010011") then
      moves <= "0010100011000000000000000001100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0010000011") then
      moves <= "0011000100000000000000010000100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0000010011") then
      moves <= "0010100011000000000000000000100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0110010011") then
      moves <= "0010100011000000000000000100100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0000000011") then
      moves <= "0011000100000000000000010010100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "1010000011") then
      moves <= "0011000100000000000000010011100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "1000000011") then
      moves <= "0011000100000000000000010100100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0100010011") then
      moves <= "0010100011000000000000000011100000000";
    elsif(fu_opcode(17 - 1 downto 0) = "01000001010010011") then
      moves <= "0010100011000000000000000110100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "1100010011") then
      moves <= "0010100011000000000000000010100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0100000011") then
      moves <= "0011000100000000000000010001100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0001100111") then
      moves <= "0001000001000000000000101000100000000";
    elsif(fu_opcode(17 - 1 downto 0) = "00000000010010011") then
      moves <= "0010100011000000000000000101100000000";
    elsif(fu_opcode(10 - 1 downto 0) = "0000100011") then
      moves <= "0011000000100000000000010111000000011";
    elsif(fu_opcode(10 - 1 downto 0) = "0100100011") then
      moves <= "0011000000100000000000010110000000011";
    elsif(fu_opcode(10 - 1 downto 0) = "0010100011") then
      moves <= "0011000000100000000000010101000000011";
    elsif(fu_opcode(10 - 1 downto 0) = "1101100011") then
      moves <= "0000101000100000000000101000000000001";
    elsif(fu_opcode(10 - 1 downto 0) = "0011100011") then
      moves <= "0000110000100000000000101000000000001";
    elsif(fu_opcode(10 - 1 downto 0) = "1111100011") then
      moves <= "0000011000100000000000101000000000001";
    elsif(fu_opcode(10 - 1 downto 0) = "1011100011") then
      moves <= "0000010000100000000000101000000000001";
    elsif(fu_opcode(10 - 1 downto 0) = "1001100011") then
      moves <= "0000100000100000000000101000000000001";
    elsif(fu_opcode(10 - 1 downto 0) = "0001100011") then
      moves <= "0000001000100000000000101000000000001";
    elsif(fu_opcode(7 - 1 downto 0) = "0110111") then
      moves <= "0010100011000000000000000000100000000";
    elsif(fu_opcode(7 - 1 downto 0) = "1101111") then
      moves <= "1010000001000000100000100000100000000";
    elsif(fu_opcode(7 - 1 downto 0) = "0010111") then
      moves <= "1010000010000000100000100000100000000";
    else
      moves <= "1010000000100000100000100000100000000";
    end if;
    if(data_hazard = '1') then
      if(rs1_hazard = '1') then
        if fu_opcode(17-1 downto 0) = "00000000000110011" or fu_opcode(10-1 downto 0) = "0000010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000000";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001110110011" or fu_opcode(10-1 downto 0) = "1110010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000001";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000001";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000001";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000001";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000001";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000001";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011000110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011000";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011010110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011001";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011001";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011001";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011001";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011001";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011001";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001100110011" or fu_opcode(10-1 downto 0) = "1100010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000010";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000010";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000010";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000010";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000010";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000100110011" or fu_opcode(10-1 downto 0) = "0100010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000011";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000011";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000011";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000011";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000011";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000011";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000110110011" or fu_opcode(10-1 downto 0) = "0110010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000100";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000100";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000100";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000100";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000100";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000100";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010000110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011010";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011010";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011010";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011010";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011010";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010010110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011011";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011011";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011011";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011011";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011011";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011011";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010100110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011100";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011100";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011100";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011100";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011100";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011100";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010110110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011101";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011101";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011101";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011101";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011101";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011100110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011110";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011110";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011110";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011110";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011110";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011110";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011110110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000011111";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100011111";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100011111";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100011111";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000011111";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000011111";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000010110011" or fu_opcode(17-1 downto 0) = "00000000010010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000101";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000101";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000101";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000101";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000101";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "01000001010110011" or fu_opcode(17-1 downto 0) = "01000001010010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000110";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000110";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000110";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000110";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000110";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000110";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001010110011" or fu_opcode(17-1 downto 0) = "00000001010010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000111";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000111";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000111";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000111";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000111";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000111";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000000001011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000110000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100110000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100110000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100110000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000110000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000110000";
          end if;
        elsif fu_opcode(17-1 downto 0) = "01000000000110011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000001000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100001000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100001000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100001000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000001000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000001000";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001000110011" or fu_opcode(10-1 downto 0) = "1000010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000001001";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100001001";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100001001";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100001001";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000001001";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000001001";
          end if;
        end if;
        if fu_opcode(10-1 downto 0) = "0001100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000101000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100101000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100101000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100101000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000101000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000101000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1011100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000101000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100101000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100101000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100101000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000101000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000101000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1111100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000101000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100101000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100101000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100101000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000101000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000101000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1001100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000101000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100101000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100101000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100101000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000101000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000101000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1101100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000101000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100101000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100101000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100101000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000101000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000101000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0011100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000101000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100101000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100101000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100101000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000101000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000101000";
          end if;
        end if;
        if fu_opcode(10-1 downto 0) = "0010100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010101";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010101";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010101";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010101";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010101";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010101";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0100100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010110";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010110";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010110";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010110";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010110";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010110";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0000100011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010111";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010111";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010111";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010111";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010111";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010111";
          end if;
        end if;
        if fu_opcode(10-1 downto 0) = "0000010011" or fu_opcode(10-1 downto 0) = "0000010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0010000011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0100000011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010001";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010001";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010001";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010001";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010001";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010001";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0000000011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010010";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010010";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010010";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010010";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010010";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010010";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1010000011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010011";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010011";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010011";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010011";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010011";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010011";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1000000011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000010100";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100010100";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100010100";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100010100";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000010100";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000010100";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1110010011" or fu_opcode(10-1 downto 0) = "1110010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000001";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000001";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000001";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000001";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000001";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000001";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0001100111"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000101000";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100101000";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100101000";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100101000";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000101000";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000101000";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1100010011" or fu_opcode(10-1 downto 0) = "1100010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000010";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000010";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000010";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000010";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000010";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000010";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0100010011" or fu_opcode(10-1 downto 0) = "0100010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000011";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000011";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000011";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000011";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000011";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000011";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0110010011" or fu_opcode(10-1 downto 0) = "0110010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000100";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000100";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000100";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000100";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000100";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000100";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000010010011" or fu_opcode(17-1 downto 0) = "00000000010010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000101";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000101";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000101";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000101";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000101";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "01000001010010011" or fu_opcode(17-1 downto 0) = "01000001010010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000110";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000110";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000110";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000110";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000110";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000110";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001010010011" or fu_opcode(17-1 downto 0) = "00000001010010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000000111";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100000111";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100000111";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100000111";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000000111";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000000111";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1000010011" or fu_opcode(10-1 downto 0) = "1000010011"then
          if target_fu_r = 0 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "111000001001";
          elsif target_fu_r = 1 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110100001001";
          elsif target_fu_r = 2 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "100100001001";
          elsif target_fu_r = 3 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101100001001";
          elsif target_fu_r = 4 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "110000001001";
          elsif target_fu_r = 5 then 
            moves(rs1_start_c + rs1_width_c -1 downto rs1_start_c) <= "101000001001";
          end if;
        end if;
      end if;
    if(rs2_hazard = '1') then
        if fu_opcode(17-1 downto 0) = "00000000000110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001110110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011000110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011010110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001100110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000100110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000110110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010000110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010010110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010100110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000010110110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011100110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000011110110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000101";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100101";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100101";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100101";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000101";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000101";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000010110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "01000001010110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001010110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000000000001011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000100";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100100";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100100";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100100";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000100";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000100";
          end if;
        elsif fu_opcode(17-1 downto 0) = "01000000000110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        elsif fu_opcode(17-1 downto 0) = "00000001000110011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000010";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100010";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100010";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100010";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000010";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000010";
          end if;
        end if;
        if fu_opcode(10-1 downto 0) = "0001100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000001";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100001";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100001";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100001";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000001";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000001";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1011100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000001";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100001";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100001";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100001";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000001";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000001";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1111100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000001";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100001";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100001";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100001";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000001";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000001";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1001100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000001";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100001";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100001";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100001";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000001";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000001";
          end if;
        elsif fu_opcode(10-1 downto 0) = "1101100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000001";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100001";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100001";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100001";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000001";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000001";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0011100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000001";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100001";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100001";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100001";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000001";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000001";
          end if;
        end if;
        if fu_opcode(10-1 downto 0) = "0010100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000011";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100011";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100011";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100011";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000011";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000011";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0100100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000011";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100011";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100011";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100011";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000011";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000011";
          end if;
        elsif fu_opcode(10-1 downto 0) = "0000100011" then
          if target_fu_r = 0 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "111000011";
          elsif target_fu_r = 1 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110100011";
          elsif target_fu_r = 2 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "100100011";
          elsif target_fu_r = 3 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101100011";
          elsif target_fu_r = 4 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "110000011";
          elsif target_fu_r = 5 then 
            moves(rs2_start_c + rs2_width_c -1 downto rs2_start_c) <= "101000011";
          end if;
        end if;
      end if;
    end if;
  end process;
end architecture rtl;
